"""Emit Gradle flavors + per-flavor Android resource overlays.

Writes three things:
  1. {app}/flavors.gradle.kts          - one productFlavor + signingConfig per company
  2. {app}/src/c{cn}/res/values/*.xml  - per-flavor colors + strings
  3. {app}/keystores/{cn}.jks          - via keystore_mint (caller's responsibility)

The static build.gradle.kts applies flavors.gradle.kts via `apply(from=...)`.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass

from .brand_synth import Palette, colors_xml, palette_for, strings_xml
from .catalog import Company
from .functionality_catalog import build_config_delimited
from .keystore_mint import Keystore
from .role_vocab import sic_role_vocab


@dataclass(frozen=True)
class BuiltFlavor:
    company: Company
    palette: Palette
    keystore: Keystore
    flavor_dir: str


def _gradle_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def write_flavor_resources(company: Company, palette: Palette, app_dir: str) -> str:
    """Write per-flavor res overlays. Returns the flavor source-set dir."""
    flavor = company.flavor
    flavor_dir = os.path.join(app_dir, "src", flavor)
    # Wipe any prior flavor dir so stale files from earlier catalogs don't leak in.
    if os.path.isdir(flavor_dir):
        shutil.rmtree(flavor_dir)
    values_dir = os.path.join(flavor_dir, "res", "values")
    os.makedirs(values_dir, exist_ok=True)

    with open(os.path.join(values_dir, "colors.xml"), "w", encoding="utf-8") as f:
        f.write(colors_xml(palette))
    with open(os.path.join(values_dir, "strings.xml"), "w", encoding="utf-8") as f:
        f.write(strings_xml(company.display_name))
    return flavor_dir


_MARKER_START = "// >>> GENERATED FLAVORS START"
_MARKER_END = "// <<< GENERATED FLAVORS END"


def write_flavors_gradle(built: list[BuiltFlavor], app_dir: str) -> str:
    """Splice flavor + signingConfig blocks into build.gradle.kts between markers.

    The build.gradle.kts file must contain a pair of marker lines; everything
    between them is replaced on every run.
    """
    build_file = os.path.join(app_dir, "build.gradle.kts")
    with open(build_file, "r", encoding="utf-8") as f:
        src = f.read()

    start = src.find(_MARKER_START)
    end = src.find(_MARKER_END)
    if start < 0 or end < 0 or end < start:
        raise RuntimeError(
            f"Can't find flavor markers in {build_file}. Expected lines:\n"
            f"    {_MARKER_START}\n    {_MARKER_END}"
        )

    signing_properties = os.path.join(app_dir, "generated-signing.properties")
    with open(signing_properties, "w", encoding="utf-8") as f:
        f.write("# Generated by apps/generator/generate.py. Do not commit.\n")
        for b in built:
            f.write(f"{b.company.flavor}.storePassword={b.keystore.store_password}\n")
            f.write(f"{b.company.flavor}.keyPassword={b.keystore.key_password}\n")

    lines: list[str] = [
        _MARKER_START + " - managed by apps/generator/generate.py",
        "    val generatedSigning = java.util.Properties()",
        '    val generatedSigningFile = file("generated-signing.properties")',
        "    if (generatedSigningFile.exists()) {",
        "        generatedSigningFile.inputStream().use { generatedSigning.load(it) }",
        "    }",
        "",
        "    signingConfigs {",
    ]
    for b in built:
        c = b.company
        ks = b.keystore
        rel_ks = os.path.relpath(ks.path, app_dir).replace("\\", "/")
        lines += [
            f'        create("{c.flavor}") {{',
            f'            storeFile = file("{rel_ks}")',
            f'            storePassword = generatedSigning.getProperty("{c.flavor}.storePassword") ?: ""',
            f'            keyAlias = "{_gradle_escape(ks.key_alias)}"',
            f'            keyPassword = generatedSigning.getProperty("{c.flavor}.keyPassword") ?: ""',
            '        }',
        ]
    lines += ["    }", "", "    productFlavors {"]
    for b in built:
        c = b.company
        vocab = sic_role_vocab(c)
        lines += [
            f'        create("{c.flavor}") {{',
            '            dimension = "brand"',
            f'            applicationId = "{c.application_id}"',
            f'            buildConfigField("String", "COMPANY_NAME", "\\"{_gradle_escape(c.display_name)}\\"")',
            f'            buildConfigField("String", "COMPANY_NUMBER", "\\"{_gradle_escape(c.company_number)}\\"")',
            f'            buildConfigField("String", "SUPPORT_EMAIL", "\\"{_gradle_escape(c.support_email)}\\"")',
            f'            buildConfigField("String", "ROLE_NOUN", "\\"{vocab["ROLE_NOUN"]}\\"")',
            f'            buildConfigField("String", "ROLE_VERB_START", "\\"{vocab["ROLE_VERB_START"]}\\"")',
            f'            buildConfigField("String", "ROLE_VERB_END", "\\"{vocab["ROLE_VERB_END"]}\\"")',
            f'            buildConfigField("String", "EXPORT_TITLE", "\\"{vocab["EXPORT_TITLE"]}\\"")',
            f'            buildConfigField("String", "MODULE_KEYS", "\\"{_gradle_escape(build_config_delimited(c, "key"))}\\"")',
            f'            buildConfigField("String", "MODULE_TITLES", "\\"{_gradle_escape(build_config_delimited(c, "title"))}\\"")',
            f'            buildConfigField("String", "MODULE_NAV_LABELS", "\\"{_gradle_escape(build_config_delimited(c, "nav_label"))}\\"")',
            f'            buildConfigField("String", "MODULE_SUMMARIES", "\\"{_gradle_escape(build_config_delimited(c, "short_description"))}\\"")',
            f'            buildConfigField("String", "MODULE_DETAILS", "\\"{_gradle_escape(build_config_delimited(c, "detail"))}\\"")',
            f'            buildConfigField("String", "MODULE_PRIMARY_ACTIONS", "\\"{_gradle_escape(build_config_delimited(c, "primary_action"))}\\"")',
            f'            buildConfigField("String", "MODULE_SECONDARY_ACTIONS", "\\"{_gradle_escape(build_config_delimited(c, "secondary_action"))}\\"")',
            f'            buildConfigField("String", "MODULE_METRIC_LABELS", "\\"{_gradle_escape(build_config_delimited(c, "metric_label"))}\\"")',
            f'            buildConfigField("String", "MODULE_SAMPLE_VALUES", "\\"{_gradle_escape(build_config_delimited(c, "sample_value"))}\\"")',
            f'            signingConfig = signingConfigs.getByName("{c.flavor}")',
            '        }',
        ]
    lines += ["    }", "    " + _MARKER_END]
    block = "\n".join(lines)

    # Replace the whole line range [start-of-marker-line, end-of-marker-line]
    line_start = src.rfind("\n", 0, start) + 1   # start of the start-marker line
    line_end = src.find("\n", end)               # end of the end-marker line
    if line_end < 0:
        line_end = len(src)
    new_src = src[:line_start] + block + src[line_end:]
    with open(build_file, "w", encoding="utf-8") as f:
        f.write(new_src)
    return build_file


def clean_stale_flavors(app_dir: str, keep_flavors: set[str]) -> list[str]:
    """Remove src/c* dirs whose flavors aren't in keep_flavors. Returns removed paths."""
    src = os.path.join(app_dir, "src")
    if not os.path.isdir(src):
        return []
    removed = []
    for entry in os.listdir(src):
        if not entry.startswith("c"):
            continue
        if entry in {"main"}:
            continue
        if entry in keep_flavors:
            continue
        full = os.path.join(src, entry)
        if os.path.isdir(full):
            shutil.rmtree(full)
            removed.append(full)
    return removed
